### ISSUE TITLE
Single undo for all inserts

### ISSUE THREAD

**Issue by VulumeCode** [nrodrigues/uuidgen#7]
Use editor.transact to be able to undo all inserts with one ctrl+z

**Comment by nrodrigues** [comment]
Hi @VulumeCode 👋🏻 I'm currently not maintaining this repo as I personally don't use atom, I'd be happy to accept PRs though, so maybe you wanna give it a shot?

**Comment by nrodrigues** [comment]
Just published 1.4.0 with your changes, thanks for your contribution!
